### ISSUE TITLE
Virtual button press from digital logic

### ISSUE THREAD

**Issue by bcoleg** [DanielOgorchock/ST_Anything#10]
Let me start by saying thank you so much for all of your development.  I definitely owe you guys a drink.  It has been very helpful for me in getting started with all of my custom sensors and controllers.  I am more of a hardware guy, so some of the programming is a little fuzzy.  Is there a way currently to send a button state based off of logic?  In my case, I have created a button panel of capacitive buttons.  I would like to be able to toggle a variable to true and have it send a button push command to ST.  I have gotten around it by assigning a pin to the value and reading the pin, but that's not very efficient especially when using the 8266.

**Comment by ogiewon** [comment]
Just to make sure I am clear, you simply want to transmit "button pushed" events from an ESP8266 to SmartThings, based on a user pushing one of your capacitive buttons, correct?

The best way to do this would be to create your own ST_Anything device class.  You could very easily start with the IS_Button class, and simply modify it to suit your needs.  You would probably need to overrride some of the InterrupSensor class' methods since you're not wanting to use traditional digital inputs.  

You'll need to be very careful to not add anything that causes delays, as that could mess up the behavior of the entire application.  Avoid blocking calls and the Arduino delay() statement.

If you don't want to go through the effort of creating your own class, you could simply issue a call from the main sketch in the form of:

```
  String strSndMsg = "button1 pushed";
  st::Everything::sendSmartString(strSndMsg);
```


This will send a string to the Parent Device Handler's parse() routine.  The naming convention is important if you are using my Parent/Child device handlers.  Also, in the Parent Decvice's configuration menu (click the small gear looking icon in the upper right corner of the device view on your phone) make sure you specify the correct number of Buttons that your application will support.  This is necessary so other SmartApps know how many buttons your device has so you can select the correct one to perform a specific action.

Let us know if this helps!
