### ISSUE TITLE
Memory leak in polling sensor causing esp8266 to lock up

### ISSUE THREAD

**Issue by ingenium13** [DanielOgorchock/ST_Anything#118]
It seems there's a memory leak with the esp8266 when using a polling sensor. I'm using the ST_Anything_Multiples_ESP8266Wifi sketch with a single polling sensor as temphumid1.

When I add the polling sensor with an interval of once per minute, it leaks about 200-350 bytes per minute. Changing the poll interval to 15 seconds leaks 400-600+ bytes per minute. 5 minute interval leaks 50-200 bytes per minute (~50 bytes when there's no poll, ~200 bytes when a poll occurs). The esp8266 locks up once it has under 4KB free. 

Debugging this is complicated by the fact that I just submitted a new pull request to add support for the Si7021 temperature and humidity sensor, and that's the only polling sensor I have to test with. The code is the existing DHT temperature and humidity code, with the addition of the Adafruit Si7021 class used in place of the DHT class. The Si7021 uses I2C to communicate.

Possible causes:
- Arduino/esp8266 I2C library is leaking memory behind the scenes
- Polling code is leaking memory
- Si7021 library from Adafruit's github is leaking memory
- Original ST_Anything_TemperatureHumidity code is leaking memory

I can attach the sketch I'm using if it would help. The same sketch (1 executor and 0 sensors) worked fine before I added the polling sensor.

Are there any tools that can debug what is actually consuming the memory? Do other polling sensors exhibit a similar issue on the esp8266? Are String objects perhaps causing the memory leak?

**Comment by vseven** [comment]
There is a known issue with the latest esp8266 libraries that cause a memory leak, believe it's 2.4 something. Revert back to 2.3 and your memory leak will go away.


https://github.com/esp8266/Arduino/issues/4497

**Comment by ogiewon** [comment]
Yep, what @vseven said above!  The leak is in the ESP8266 WiFi library. V2.3 does have this issue.

**Comment by ingenium13** [comment]
Thanks! Revering to 2.3 fixed it. Free Ram is stable and stops changing several minutes after boot.

**Comment by ryanfort** [comment]
I must be confused, but before using ST_Anything, I didn't seem to have this leak, I didn't see it in the console of any of my units, and they've been running for months without issue.  I just got into ST_Anything yesterday, and noticed the memory leak happening, and just cloned the repository yesterday, so I know I have all the latest libraries and sketches.  So I am not sure what I need to downgrade in order to fix this memory issue, specifically?  I checked what libraries I have installed, and I saw nothing pertaining to "2.4" and WiFi...

Otherwise, awesome product you have here, really enjoying it!
