### ISSUE TITLE
Documentation Links and Additions?

### ISSUE THREAD

**Issue by Humancell** [DanielOgorchock/ST_Anything#14]
Hello,

This looks like an awesome library, referenced by several projects.  I'm still a little unclear on the exact architecture and operation however, and was curious if you could post some additional links that could address a few of these questions?

Just for context, my goal is to create a LAN device with a set of push buttons that can be used to trigger ST apps.

1. Does ST detect this as a LAN device?
2. Can this library be used to generate the "Button Press/Hold" events to the ST hub that ST will recognize in the ST apps?
3. Are their links to any explanation or diagram of your library, and the "flow" of how it's working?
4. Does everything route through the cloud?

I'm not sure that I'm even on track, but I'm very familiar with LAN communications, web services, and the Arduino/Ethernet/ESP8266 development world.  I"m mostly unclear about how I can create a device that can interact with the ST hub locally on my LAN ... or can I?

**Comment by ogiewon** [comment]
1.  SmartThings does recognize this as a LAN connected device, however it is not auto-discovered.  You have to manually create the ST device and then configure a few settings.
2.  Yes, ST_Anything supports both the button pushed and held capabilities.  See any of the ST_Anything_Multiples example sketches to see how the buttons are implemented.  
3.  The ReadMe has a high level flow diagram.  The ST_Anything library is really an engine that is configured by the sketch.  It handles all I/O monitoring and updates, as well as all communications to SmartThings.
4.  All data flows through the ST hub. Since this is considered custom ST code, all of the groovy code runs in the cloud.  ST does not allow any custom code to run on their hub, unfortunately.

**Comment by ogiewon** [comment]
Closing issue due to lack of response by creator.
