### ISSUE TITLE
Child RGB Switch potential error when color red specified.

### ISSUE THREAD

**Issue by mlampkin** [DanielOgorchock/ST_Anything#162]
In device handler function setColor(Map color), when a request is made through other automation systems e.g. Alexa - it is sent usually as a hue and saturation.  For the color red, the hue is going to be zero ( and saturation at 100 ) and the current check is:

if (color.hue && color.saturation) 

This will evaluate to false during the color.hue check and the color will not be set.  Change to check for presence of the hue key in the map instead via:

 if (color.containsKey("hue") && color.containsKey("saturation"))

Michael

**Comment by vseven** [comment]
SmartThings has some helper functions now built into the color utilities that can be used to make this device Handler a lot smaller so the entire thing needs a rewrite (Re:https://github.com/SmartThingsCommunity/SmartThingsPublic/issues/3625 ).  Just haven't had time to do so.

With that said there is no reason to even check for hue and saturation. If HEX wasn't passed in then the only other option would be hue and saturation so it should just be an else instead of a else if.  That would be the quick fix.  The longer fix would be to remove the entire hsltoRGB function and use the SmartThings built in one:

def rgb = huesatToRGB(value.hue, value.saturation)
