### ISSUE TITLE
Buttons not creating

### ISSUE THREAD

**Issue by drgruney** [DanielOgorchock/ST_Anything#17]
Hello,

I'm using the ST_Anything_Multiples_ESP8266WiFi.ino sketch on a Huzzah Feather 8266 board. Everything *except* the buttons are showing up in my SmartThings app. 

Is there any reason why the button devices would not populate while everything else does? I have searched the ST forums and not found anyone else with this issue.

**Comment by ogiewon** [comment]
You won't "see" any buttons in the Parent Device, but they are there and will be handled correctly, assuming you've defined the correct number of them in the Parent Device's Configuration Settings.

ST_Anything supports both the "pushed" and "held" events.  You define how long an input must be high before being classified as "held" in the constructor of the IS_Button devices in your sketch.  Read the comments at the top of IS_Button.h or .cpp for the details.

**Comment by drgruney** [comment]
Thank you for the quick response! I will check there and get back.

**Comment by drgruney** [comment]
I have these lines

 `static st::IS_Button              sensor4(F("button1"), PIN_BUTTON_1, 1000, LOW, true, 500);
  static st::IS_Button              sensor5(F("button2"), PIN_BUTTON_2, 1000, LOW, true, 500);`

In the exmaple sketch, unchanged. And looking at IS_Button.h and .cp I believe everything is correct in the sketch.

If the buttons are configured, where would they show up if not in my Things list or under the parent device (which is seems to be functioning properly with all other children)?

**Comment by ogiewon** [comment]
I have just uploaded a new Parent DH to the Guithub repository which has a new tile showing the number of defined buttons.  Please give this version a try so that you can at least see that the parent knows about the buttons.

As for "where do they show up?"  Buttons show up in the SmartApps that use them.  The Aeon Minimote Device Handler, for example, has one tile with a remote control icon on it.  Nothing else.  It also has zero configuration options as well.  I used this as a model for adding "Button" capabilities to ST_Anything per a user request. 

When you define the number of buttons (via the gear-based configuration menu in the parent DH) you are announcing to all SmartApps the number of buttons defined.  This in turn allows SmartApps like "Smart Lighting", "CoRE", and "WebCoRE" to know how many "buttons" to offer you to configure an action.

So, the easiest test is to create a new "Smart Lighting" automation, where you define the action to be based on a button "pushed" or "held" event.  Give it a try and let me know how it goes.  I have used this successfully in the past for testing purposes.

**Comment by drgruney** [comment]
Oh thank you, that makes sense now. I've just gotten so accustomed to seeing everything broken out in the Things list.

I will check out the updated handler momentarily.

**Comment by drgruney** [comment]
Automation worked like a champ! Updated DH is not giving me the tile listing number of buttons. I even removed and recreated the parent device to make sure.

None the less, things are working properly ... now that I get how it actually works :). All there is to do now is fiddle with times for push/held. 

Thank you so much for the assistance. I'm closing this issue.

**Comment by ogiewon** [comment]
Did you remember to publish the new version of the parent DH?

**Comment by drgruney** [comment]
Ah ha! that did it.

I greatly appreciate all the help! Your project is great!

I have it running two buttons to control a ceiling fan. Unfortunately the Huzzah Feather isn't quite powerful enough to ALSO run the Philips Hue controller I've programmed. So I seem to be limited to button "holds" instead of presses and holds for ST.

I look forward to doing more functions on a full fledged Arduino soon.
