### ISSUE TITLE
TCP messages

### ISSUE THREAD

**Issue by rhamblen** [DanielOgorchock/ST_Anything#18]
Hi
This is great and I have it all working with Smartthings and a ModeMCU board.  I can do all sorts of switching and sensing in minutes.
What I want to do is create a way to send a Telnet message to a device like the TV to turn it off.
I have some base code for that and it works.
However, I am not sure of the best way to integrate it into your software and I am getting errors when I create a new switch (as an executor) with a different name so I can modify within that setting.
Can you add some instructions on how I can create a new executer or whether I should just add code in an existing switch to run extra code.  (which it looks like would be in the EX_switch.h  where I would call my new functions for the telenet call)

thanks
R.

**Comment by ogiewon** [comment]
The simplest method to add a new class is to start with an existing one, and then modify it to suit your needs.

1) Copy EX_Switch.h and EX_Switch.cpp to EX_SerialSwitch.h and EX_SerialSwitch.cpp
2) Edit both of these files changing every reference of EX_Switch to EX_SerialSwitch
     a) remember to modify the  "#ifndef ST_EX_SWITCH" and "#define ST_EX_SWITCH" lines near the top of your new EX_SerialSwitch.h file as well to be "#ifndef ST_EX_SERIALSWITCH" and "#define ST_EX_SERIALSWITCH"
3) Modify your new .h and .cpp files to issue your Serial commands versus the digital output updates it currently does.  Also, you will probably want to pass in a "Serial" object to the new class instead of a pin number.  In your new class's constructor or init() routine, be sure to set up the Serial device you passed in using a Serial.begin() command.  You will need to also pass in the baud rate you want to use as a constructor argument.  You could even pass in an string for the "on" command and another for the "off" command.  This would keep your new class very generic and not specific to any one device (e.g. TV).
4) In your sketch, be sure to #include <EX_SerialSwitch.h>
5) In your sketch's setup() routine, be sure to use the st::EX_SerialSwitch constructor instead of the standard EX_Switch.

Hope this helps to get you started!

**Comment by ogiewon** [comment]
Closing due to no recent updates for over a month.
