### ISSUE TITLE
comm issue between Mega/ESP01 and Smartthings Device

### ISSUE THREAD

**Issue by Autom8or** [DanielOgorchock/ST_Anything#19]
I'm using a Mega with an ESP01.  I've fired them up and verified them with AT commands and am now trying to use ST_Anything_Multiples_MEGAWiFiEsp.ino and run it with Smartthings.  It connects to the access point (with a static IP) and initializes all the sensors, but reports errors every time it tries to send a message:
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Data packet send error (1)

I can ping the ESP01 fine.

I have a device added, using the Parent_ST_Anything_Ethernet Device handler and the corresponding IP address, port, MAC and buttons configured on my mobile device.  The Parent device seems to run OK, based on the Event log, but does not try to add any Child devices.

Any suggestions?

**Comment by ogiewon** [comment]
Just saw this issue...  sorry for the slow response...

I too see the ESP01 timeouts from time to time.  I spent about a week trying to perfect the Arduino MEGA/ESP01 combination and what you see is as good as I could get it.  I am not convinced that the MEGA + ESP01 is truly a stable WiFi solution.  I have also tried using the Adafruit ATWINC1500 WiFi module with an Arduino MEGA and it too suffers from stability issues.  So I bought an Arduino MKR1000 thinking that would be the most stable platform since it is an all-in-one Arduino + WiFi solution.  Guess what?  It uses the same flaky ATWINC1500 WiFi chip which seems to still have quite a few bugs to work out in its firmware.

Finally, just this past week I have added support for the ESP32 Dev Boards.  Check out my ReadMe for a link to the board I bought from Amazon for ~$13.  It is like a NodeMCU ESP8266 board, but with about 23 usable GPIO pins!  So far, the WiFi on it has been stable, but I don't have a ton of run-time on it yet.

**Comment by Autom8or** [comment]
Thanks for getting back and for the suggestions - I've gone over everything many times to see if I just missed something or mis-interpreted it. I've also tried different ESP001 modules. My timeouts are not occasional, but on every SendData message - I have not seen one succeed.  I will check out the ESP32 next.

 

BTW - I also observed some anomalous behavior when I first tried the code.  The messages from ST_Anything in the serial monitor were actually reporting the last octet of the MAC address incorrectly (I considered the "correct" MAC to be what I could read from the board directly using AT commands or observe on the network using Wireshark). I tried it with two boards - one consistently (through ST_Anything) reported 07, instead of F4, the other consistently reported 75, instead of 45.  the first five octets were always right.  Recently they seem to be reporting the right MAC, and I can't identify anything that has changed.  I tried both the "correct" and "incorrect" MACs in the ST_Anything device configuration, but neither affected the Timout behavior - I got the impression from some of the comments, that the MAC entry might not be essential, but I thought I'd pass on the observation.

**Comment by ogiewon** [comment]
"BTW - I also observed some anomalous behavior when I first tried the code.  The messages from ST_Anything in the serial monitor were actually reporting the last octet of the MAC address incorrectly"

I have witnessed this behavior as well, and I thought I had put in a reliable fix for that issue.  Are you running the latest version of all of the libraries?

**Comment by ogiewon** [comment]
One more thing...  I noticed that running the Arduino's "Serial" port at 115,200 significantly reduced the number of timeout events.  This is now the default in ST_Anything.  You didn't happen to change it?

Also, you need to make sure that the loop() routine executes very quickly, without any long-running custom code (delay() statements inside the loop() are a very bad idea!)

**Comment by Autom8or** [comment]
I am running the latest libraries now - that's probably what changed the behavior and why I haven't been able to reproduce it lately.

 

Thanks.

**Comment by ogiewon** [comment]
Okay.  Thanks for the update.  I am going to close this issue as I really am out of ideas to try to make the MEGA + ESP01 any more reliable.  If you figure out a fix, please submit a pull request.

**Comment by Tokn59** [comment]
You are absolutely tight ! I have tried mutiple times with severeal ESP-01 .. they are simply unreliable ...
