### ISSUE TITLE
Feature Request: Bluetooth debug for ESP32

### ISSUE THREAD

**Issue by genesisfactor** [DanielOgorchock/ST_Anything#207]
Awesome job on this library!

Currently, we have hardwared serial debug.  It would be great to have bluetooth serial debug, so we don't have to power down a ESP32 device and attach it to our computer.  This is especially useful for when the problems may only arise when plugged into "at location" power instead of just serial port, like i'm currently facing.

**Comment by ogiewon** [comment]
I fear this feature, while useful to a select few, would not be useful to a large enough user base to justify the amount of time and development required to implement.  ST_Anything runs on a large variety of microcontrollers, most of which do not support Bluetooth whatsoever.  The ESP8266 is probably the most popular platform currently, and it does not support Bluetooth.

**Comment by vseven** [comment]
Although I agree with @ogiewon that not a lot of people would use this ability I also think it would be a cool thing to have.  I've been doing a lot of testing with LED strips and as part of that I've been powering my ESP32 off of the 5v power supply that the LED strips use.  As such I haven't been plugging in USB for troubleshooting since it may back-feed into my computer.  Having BlueTooth serial monitoring would remove that risk.

I'll see if I can take a stab at this....

**Comment by vseven** [comment]
So the initial setup of this on a ESP32 is really simple.  The problem is going through and changing all the serial.println to use it.  Or if there is another way to do it that I don't know about that maybe Dan does where something can redirect those globally.  But for a hack way of doing it you can use the callback to at least see whats being sent.

@ogiewon - This is really easy to add to the ESP32 and can just be defaulted to commented out.  Gonna put it into the ESP32 multiples for now.

**Comment by genesisfactor** [comment]
So if you up came create a global flag for BT setup, maybe you can just have to do if statements with SerialBT() where ever Serial() is called?

**Comment by vseven** [comment]
Yup.  But thats not something I'd want to undertake.  The hack works well enough to at least see whats happening a bit.   Here's the pull request if you wanna play with it:  https://github.com/DanielOgorchock/ST_Anything/pull/210/commits/aef18e8a2c33005440e556ea58374fa4b26fc1a1

**Comment by genesisfactor** [comment]
Hehe I almost did a PR, and got caught in those print statements, based on the docs.  But I don't even know if I'm doing it right enough to be worthy.  A mix of low dev self esteem and low bandwidth lol.  I'll check it out though!  If you give me the flag, and a template, I'll do some grunt work and test.

Another way I thought about was having a debug mode and connecting over wifi and reading a log file. It's not as good as BT, if wifi connectivity is the issue, but that might be lower hanging fruit...

**Comment by vseven** [comment]
The problem it to do it "right", I think, you'd have to pass the BlueTooth object to everything and update pretty much every device handler.  I'm just not sure if it's worth it when you can grab the basics from the callback routine.

**Comment by ogiewon** [comment]
That's exactly correct...  There are a ton of Serial.print() statements throughout the library that would all need to be abstracted into a user selectable logging library.  Some might want Bluetooth, while others might prefer Syslog, or a webSocket, or some sort of UDP messaging, etc...  I have thought about it, but it just really isn't worth the effort - especially when only a few microcontrollers support BT.  Thus, I would be reluctant to support such a massive Pull Request to ST_Anything.

I like the idea of just sending some debug out via the callback() method in the sketch.  That's a nice, simple solution.  Great idea Allan!

**Comment by vseven** [comment]
Since this code was added in PR 211 (https://github.com/DanielOgorchock/ST_Anything/pull/211) I would think this can be closed.
