### ISSUE TITLE
Ky-040 rotary encoder with ST_Anything

### ISSUE THREAD

**Issue by al3sh** [DanielOgorchock/ST_Anything#235]
Hi,
I want to connect a KY-040 rotary encoder to my motorized blind. I intend to hook up the encoder to the blind axis, this way I could get the status: open, closed, open at 50%, 30% , etc. I was thinking this device could be show as a dimmer switch.
My current setup: 

- I use a relay board to activate the blind. This button open/closed/stop the blind, one click move the blind, a second click moves the blind in the oposite direction. 
- I'm using a ESP8266.
-  a KY-040 encoder to get the level.

I appreciate any help or direction.

Thanks!

**Comment by ryancasler** [comment]
You're saying that you use the rotary encoder to confirm the location of where the blind is currently?  Are we talking horizontal blinds like these:
![image](https://user-images.githubusercontent.com/30270489/99158533-b39e0580-26a1-11eb-99d3-8b926908888b.png)
Or are we talking a shade, like this:
![image](https://user-images.githubusercontent.com/30270489/99158542-cd3f4d00-26a1-11eb-9787-9049618e4299.png)

I'm going to assume that you are talking about a shade.  I'm also going to assume that you are using a simple DC motor as the driver.  So, how are you using the rotary encoder to confirm the shade's position?  The rod is going to rotate several times while the shade is raising or lowering.  So, you would only be able to use that to keep track of the location.  What would be much easier is to use a stepper motor and simply count the number of steps that you are moving in either direction.  In either case, it requires that the board keep this location in static memory that will not be lost when you pull power.  Otherwise, you would have to re-home the shade after every boot.  ST_Anything doesn't have a way (built into it) to store data except what is stored in the sketch.  So, you couldn't for example,  remember where the shade was when you pull power from the board and plug it back in (or have a power outage).  The shade would have to go all the way back to home AND have some type of sensor to tell it that it was home, in order to use this method.  For this reason, I have all my  stepper motors on other sketches as ST_Anything doesn't have a way to do this.

**Comment by ogiewon** [comment]
closed due to lack of activity.
