### ISSUE TITLE
comm issue between Mega/ESP01 and Smartthings Device - Good News!

### ISSUE THREAD

**Issue by Autom8or** [DanielOgorchock/ST_Anything#40]
This is round two, since we closed the original issue, but I found what looks like the real problem and a potential solution.  I'm opening a new issue rather than the pull request, because the workaround I found didn't require any immediate code changes (although it might suggest some improvement).

I was really bothered by the fact that my timeouts happened every time the ESP01 tried to send data.  You had intermittent success that I had been unable to reproduce, with the unmodified project. I will probably move to the ESP01 standalone at some point, but I figured I had to at least get something going with the ESP01 before moving on.  It was configuring fine and opening the connection successfully, but would always get a timeout on every sendData call. I turned up the log message level and could see that the ESP01 was responding with "ERROR" [apparently to the AT+CIPSEND]. So I went back to a simple sketch where I could issue the AT commands myself and see them echoed with their responses. Sure enough, I had the same results - I could go as far as opening a connection, but I always got ERROR for a response. I also saw that the reason why it responded with ERROR (and hence, the <<TIMEOUT >> on ST_Anything) was because the connection would close on its own before I could  deliver the AT+CIPSEND call. This was not apparent from the ST_Anything log messages (I don't know if the driver wasn't watching for a response after it saw the initial OK or if it just didn't generate a log message).

Anyway, it was obvious that the ESP01 was not able to keep the connection open long enough to send data.  I also saw some characters dropped in the Serial Monitor when the ESP01 was responding with larger messages. These started to suggest possible hardware issues.

I was reading up on the 8266 and had an Ah Ha moment while reading Neil Kolban's book on the ESP8266 (a great read in general). He points out that the current draw of the chip goes from microamps to a couple hundred milliamps when transmitting and suggests putting a 10 uF cap on the the 3.3V supply near the ESP01. I've seen major issues with devices whose load varied a lot less, so I added both a 220uF cap and a .1 uF decoupling cap at the ESP01 connector on my prototype shield. When I ran ST_Anything again, I still had timeouts on all transfers for quite a while, but saw it actually recover later on and then work occasionally. I figured I was on the right track, so I hooked up a scope and saw significant swings not only on the 3.3 line (I had built my own 5V -> 3.3V regulator on the shield), but also saw smaller, but still disturbing shifts on the ground level at the ESP01. This suggested a couple of potential contributors. I realized that the small wires I used to connect everything, while very short, were undersized for the current load and I was also aware that all the ground pin connections on my prototype shield are not actually connected together on that board (they rely on the fact that they are all connected on the Arduino [Mega] I was using).

So then I ran heavy bus wires between all the ground pins I was using and the various key points of circuitry subject to the load variations. I also increased the wire delivering 5V to my regulator and 3.3 to the ESP01. Now, when I ran ST_Anything, I still saw timeouts for the first few transfers, but it recovered and actually worked well most of the time, but still with occasional timeouts. 

Being further encouraged, I grabbed a larger capacitor (3300 uF was what I had on hand) and soldered it directly to the GND & 3.3V pins of the ESP01.  I ran ST_Anything again and it was successful from the start.  I've run it now for most of an hour and only seen 4 timeouts. These timeouts are not on the first send to a new connection and appear to be more random. It does not try to reopen and re-send the data from that specific device, but moves on to the next one, which is probably fine if they are very occasional.

My takeaway is that Neil hit it on the head with his observation, and has probably even understated the concern. His book shows an ESP01 connected to a breadboard with long jumper wires. I suggest anyone connecting this or any similar board use a large cap near the device, pay close attention to the size and length of conductors in the ground path and don't rely on multiple pins to connect various grounds.  I also plan a minor mod to my 3.3V supply to minimize voltage shift under widely varying loads and I'll find a physically smaller cap to put by the ESP01 and still does the job.

It might be worth considering a code change that will re-connect and re-send a child device's message if it doesn't succeed. at would also be good to catch the unintended close of the connection and add a log message for it.

Feel free to close this second issue - I just wanted to pass on what I found.

Cheers,

**Comment by ogiewon** [comment]
Thank you for the detailed write up!  I am sure this will help others as well who attempt to use the ESP01 as a WiFi shield for the Arduino MEGA. 

Your experience sound very similar to mine.  I too attempted to build a very robust 5v to 3v power source for the ESP01, used a 5v to 3.3v level shifter for communications, shortened my wires as much as possible, added a capacitor to help with power fluctuations, etc...   Here is a picture of what my MEGA + ESP01 looks like today.  

![img_2124](https://user-images.githubusercontent.com/5206084/29850170-abffd7da-8cf9-11e7-8482-55b889b8a02b.JPG)


As for the retry logic for sending a message, I actually did implement code to do exactly that when I realized that I was getting errors most frequently on sending data.  Sounds like you found the exact same thing!  At least it is behaving somewhat consistently for both of us.

All of the code that interacts directly with the ESP01 module (when used as a WiFi shield via the serial AT command set) can be found the the ...\Arduino\libraries\SmatThingsWiFiEsp\ library.  There are only two files in that library.  Please note that these files inherit from a parent C++ class in the ...\Arduino\libraries\SmatThings\ library.  The whole design is to make everything modular for the ST Communications layer.  This is what allows me to easily add support for new microcontrollers and/or network connectivity methods.  The main ST_Anything library has no idea which method is being used to communicate to the ST Hub.

Anyway, the retry logic for sending data can be found in SmartThingsWiFiEsp.cpp, specifically in the void SmartThingsWiFiEsp::send(String message) function.  It attempts to retry sending once if it fails the first time.  If you look in the code, you can see where I attempted various reset and re-initializations of the ESP01 module.  These attempts always seemed to make things worse.  I have learned that the ESP8266 modules, including the ESP01, seem to do a great job of automatically reconnecting to WiFi if the signal is dropped for any reason (e.g. you reset your home router, or a power blip, etc...)  Trying to force a reconnection always seemed to result in locking the system up.

Feel free to try to make the logic better at recovery.  I spent the better part of ~2+ weeks trying to get this to run reliably.  I also bought a ATWINC1500 (aka WiFi101) from Adafruit, and built a custom Arduino shield for it.  Unfortunately, that platform is also error prone and drops off the network all the time.  Unfortunately, it does not automatically reconnect.  Therefore, I built in a bunch of recovery software for that platform.

![img_2125](https://user-images.githubusercontent.com/5206084/29850187-bbf5250a-8cf9-11e7-96f1-85552ec6cb88.JPG)


Finally, I bought an Arduino MKR1000 hoping it would be reliable since it has built-in WiFi.  Unfortunately, it uses the same ATWINC1500 WiFi chip and thus suffers the same problems as my custom WiFi101 shield.  If you look at the WiFi101 library's GitHub page, you'll see a bunch of people having issues with the WiFi101/ATWINC1500 platform.  ATMEL needs to upgarde their firmware to fix a lot of the issues, IMHO.   

I would really love to find a solid, stable, reliable WiFi should for the Arduino MEGA.  If you find one, please let me know!  I would be happy to help integrate it into ST_Anything.
