### ISSUE TITLE
Callbacks for messages/events received?

### ISSUE THREAD

**Issue by flynnwt** [DanielOgorchock/ST_Anything#52]
I am adding ST integration to an existing ESP8266 program and it works fine, but I don't see a way to set up callbacks to handle actions initiated from the web (like a switch turning on/off).  The gpio changes state, but local code to handle the state change isn't notified like it is for http requests/websocket messages, unless polling is added to loop() to check for state changes (unless I missed how to set this up).

A generic 'all-message' callback and something like msgRcvd(msg) and onChange(newVal) for switches, etc. would be useful to manage devices where 2-way control is possible.

**Comment by ogiewon** [comment]
There is a callback function in every example sketch that is called whenever data is sent to ST. Since this happens for almost every event (in either direction) you can use this to see what has changed and take appropriate action. 

Note: it is very important that none of your custom code has any delay() or long-running loops which could cause delays to the the Everything::run() command.

**Comment by ogiewon** [comment]
Should have asked- Are you using the full ST_Anything library, or just the SmartThings library?  If the latter, you get to control everything yourself, just like with the old ThingShield.

**Comment by flynnwt** [comment]
Thanks, I saw the callback for sending.  I will look at that later to see what messages are sent after receipt.  I am using the ST_Anything library.  I just need to maintain consistent internal state, so I won't be running any loops, etc.

**Comment by flynnwt** [comment]
OK, I see the messages like 'switch1 off'.  Instead of parsing all the messages, I ended up extending EX_Switch to Ex_Switch_2W and added callbacks.
