### ISSUE TITLE
WiFi Auto Configure & SSDP Support for Device Discovery

### ISSUE THREAD

**Issue by randuhmm** [DanielOgorchock/ST_Anything#8]
I have recently started a very similar project on ESP-01 microchips. However, I have some different features that might be useful to optionally enable so that users will not need to re-flash the device when WiFi or Network configurations change. These features can be summarized as follows:

1. I am using the `WifiManager` library (https://github.com/tzapu/WiFiManager) to handle auto-configuration of the WiFi settings. This library allows the device to host an AP and, using a smartphone (or some other WiFi client), you can open a browser and be routed to a configuration page to join the desired WiFi network. This is similar to how WiMo and various other consumer devices are configured. Additionally, the device saves the credentials in flash and I also have a "reset" button that can be used to reconfigure the device if it needs to switch networks.

2. To handle device discovery with SmartThings, I am using a custom SmartApp as a Device Manager to handle the SSDP requests and responses for adding new devices. When a new device is located, the user can select it and it will be automatically configured and it's Device Types will be added. The SmartApp uses an HTTP API to detect exactly which Device Types should be enabled.

With my project, I do have some issues that mostly stem around handling UPnP `NOTIFY` events. I am pretty sure that I must have a parent Device Type that receives all UPnP events and forwards them to the appropriate device. I think you have already seen this issue and solved it with the parent Device Type.

Anywho, in a nutshell, enabling these features would eliminate the requirement for static IP addresses to be assigned to all devices and the hub. I think this greatly simplifies configuration and deployment of new devices. I am open to thoughts on if/how these features might be included into this project. I am also happy to help move the process along with my knowledge on the matter. 

Thanks!

**Comment by cookejames** [comment]
Just to chime in on this but I agree with the above. I would at least like to use Wifimanager and DNS names rather than IP addresses so that I don't need to hard code my wifi credentials or setup static IP addresses for all my devices.

I have also setup a micro http server that provides all the details of the device (IP address, MAC etc) that you can query. This way you can just browse to say http://mydevice.local on your own network and get all the details you need rather than having to connect to the serial port.

Do you accept pull requests? I would at least like to push in my version of the ESP8266 class that just verifies that a wifi connection is available rather than requiring

**Comment by ogiewon** [comment]
Yes, we certainly do accept pull requests and we welcome the feedback and appreciate the development assistance!  One of my concerns is maintaining backwards compatibility.  Therefore, I believe you could add a new constructor to SmartThingsESP8266WiFi class which would implement the WiFiManager, instead of the STATIC or DHCP addressing currently supported.  If possible, I would prefer to not add any new code to the Arduino sketch in support of WiFiManager if that is possible.  Hopefully, your changes can be implemented within SmartThingsESP8266WiFi.h and .cpp.   Of course, the Arduino sketch will need to be modified to call the new constructor instead of the current ones (i.e. static or dhcp).

Looking forward to seeing what you come up with!

**Comment by cookejames** [comment]
Yep a new constructor would be enough and I think it would be completely transparent to the existing code. Its only a few lines of code - probably just to check that the wifi is connected.

SSDP is the more interesting part - I'd really like to avoid static IP addresses as I tend to create a lot of ESP8266 widgets. I saw on the smartthings community forum that you were thinking of adding support for this. Have you done any work on it? 

I'm new to smartthings having previously just rolled my own solutions however SSDP on the ESP8266 looks really easy to implement as there is even a full guide in the docs on how to create a SSDP smartapp.

**Comment by ogiewon** [comment]
cookejames - Thanks you for the pull request.  Glad you were able to implement a very simple, backwards compatible change to allow you to use the WiFiManager with the ESP8266.

randuhmm - Are you still working on your changes?  Or should I close this issue for now?  Please let me know.  

Thanks!

**Comment by randuhmm** [comment]
Hey @ogiewon ,

After taking a deeper dive into the code, it seems that this framework is specifically targeting Arduino boards which have WiFi enabled via a separate module (such as the WiFi shield, or an expressif ESP board with AT commands). The project I have started is more geared towards directly flashing the ESP modules with firmware that implements both an HTTP server/client as well as a SSDP server in order to allow auto discovery, configuration and communication with the SmartThings hub. I am working on standardizing my HTTP communication into a Pub/Sub API specification (http://rad-esp8266.readthedocs.io/en/latest/specs.html) which should allow me to implement the spec on other devices as well to allow them to also connect and reuse the same SmartThings code for SmartApps and DeviceHandlers.

I do not have much experience at all with WiFi on Arduino boards so I am unsure how I would implement SSDP. I believe the WiFi shield and ESP modules communicate with the Arduino via Serial commands, is that correct? A SSDP server would need to listen for multicast messages on the multicast IP address of the subnet. I am not certain that this is possible with only AT commands provided by the default firmware. 

The more I investigate this framework, the more I am amazed at all the incredible features you have packaged in such a constrained environment! However, it seems to me that trying to cram in more features such as WiFi auto configuration and SSDP might not be the best idea for this project. What are your thoughts?

**Comment by cookejames** [comment]
@randuhmm my aims are very similar to yours. I'm looking to auto configure custom devices similar to the [sonoff](https://community.smartthings.com/t/release-sonoff-sonoff-th-s20-dual-4ch-touch-device-handler-smartapp-5-10-smart-switches/45957) integration. However I would like the flexibility that st_anything offers for writing new classes for sensors.

I'd agree with you I have no idea how to implement SSDP over a serial bridge - I'm not sure it is even possible.

**Comment by randuhmm** [comment]
@cookejames - If you are interested in working directly with the ESP8266 modules, then perhaps my framework is what you are looking for. I am expecting it to work with sonoff devices as well as other generic sensors. Some of the finer details are still a work-in-progress, but I expect to have examples for simple (binary) sensors soon as well as multi-level and rgb switches.

**Comment by cookejames** [comment]
@randuhmm sounds interesting. The ESP8266 is certainly my main focus as I have so many of them and they have such good library support. I think ST_Anything is great - it looks really well written and thought out - its just that I don't want to have to have to support thingshields and serial wifi devices that aren't relevant to me. I don't know how far you've gotten with your library but you could certainly do well by starting off with a fork of ST_Anything for most of the Arduino functionality.

**Comment by ogiewon** [comment]
@randuhmm - You are correct that ST_Anything v1.x began its life as a framework geared specifically at the Arduino + ThingShield platform.   With v2.x, I have added support for numerous Arduino boards as well as the ESP8266 boards.  These can all be connected to SmartThings now via network connections (Either WiFi or hard-wired depending on the board/shield combination.)  

I believe this provides an incredible amount of flexibility for various use cases.  Need just a tiny board?
  You can run ST_Anything natively on the ESP01.  Need 70 GPIO pins?  Use an Arduino MEGA with a network shield (hard wired or WiFi.)  The libraries take care of all of the device specific logic, polling, and SmartThings communications, in a lightweight, robust manner.

I'll be honest, I haven't really looked too hard at SSDP or UPNP protocols for discovery.  I believe most users are going to set up a few of these devices for a custom integration.  It doesn't seem like a lot to ask that they statically assign an IP address or two, since they have to compile the project to use their desired pins and to define the attached devices.  I did recently add DHCP based constructors for those users who would prefer to use static DHCP assigments via their routers.  This at least allows users to change the LAN address of their micro-controller without having to recompile.  

That being said, I never intended for any of this code to be used commercially.  If I was trying to mass produce a gadget and sell it into the mass consumer market, I believe many changes would be in order.  My son and I have discussed a solution where the user never defines anything on the micro-controller.  Everything would be defined via a SmartThings SmartApp, via some sort of wizard based solution.  It would be 100% configurable, without the need to write any code.  I believe this would make sense if we were trying to sell these gizmos to the masses.  Currently, this is mostly just an idea though... :)

However, I believe the home electronics hobbyist/enthusiast is currently the group that even considers using an Arduino or ESP8266 micro-controller in the first place.  These users want to roll up their sleeves and write some code.  We encourage users to add new device classes to ST_Anything as they see fit to achieve the goals of their projects.  

Just to try to make sure the ST_Anything Architecture is clear (see the ReadMe for a graphical slide)...
-Aside from the ThingShield solution, all other solutions utilize Ethernet for connectivity.  
-The "SmartThings" library abstracts all of the ST connectivity away from the ST_Anything library. 
-The "ST_Anything" library is responsible for keeping track of all of the devices attached to I/O pins.  It then handles incoming/outgoing data from/to the SmartThings library (e.g. turn a switch on, update a contact sensor, notify of a button press, etc...)  
-The SmartThings library handles all communications to/from the ST Hub and ultimately the ST cloud.  
-The users code never needs to worry about how the code communicates to the network devices (except for setup info).  In some cases, serial I/O is used to communicate to a WiFi shield or an Ethernet Shield.  The method of connection is irrelevant to the Arduino networking code.  In all cases of LAN-connected devices, there is a Ethernet Server and Client being used to communicate to the ST Hub.  This code all lives exclusively within the SmartThings library.  

All that being said, I do believe that focusing on a single platform will allow you to exploit all of that device's capabilities more fully.  In that respect, I believe you are right about the ESP8266 being a fantastic, low-cost platform for iOT projects.  It has quite a bit of memory and a quick CPU, making for a very nice package.  I also have found its WiFi connectivity to be the most robust in all of my testing.  Be aware that it is quickly being joined by the newer ESP32 chip from Espressif.  As such, your project may soon face the reality of trying to support multiple platforms as well! ;)  

For now, ST_Anything is maintaining the same functionality across all of its supported hardware platform combinations.  I am not sure how long I will be able to keep everything common across all of the platforms, but for now that is goal.  

I am enjoying this conversation as I know ST_Anything can still grow into something bigger and better.  Having users like you and @cookejames contributing your ideas and code is very welcome.  

Thank you both for the feedback and discussion!

**Comment by randuhmm** [comment]
Wow! Thanks for the very informative and enlightening post. I can agree with pretty much all the points you are making. I especially like the flexibility of ST_Anything with regard to it's ability to serve the needs for a very small connected device or a massive one (controlling 70 GPIOs @_@). Also, the feature to enable DHCP sounds like and awesome way to afford users of this library some more flexibility.

I had no idea how much this project has evolved and I am quite impressed with how you have been able to keep up with the improvements SmartThings has been making over the years. I am very interested in the updates you recently made to the DeviceHandlers for the new parent/child component enhancements. For my project, I am using a SmartApp for the SSDP discovery portion which, in-turn, creates the various parent and child DeviceHandlers. I am not certain if this is similar to what you are doing or if it's even the best way to configure the discovered devices. This is all very hard to explain via text, as I'm sure you understand. I am still working on organizing and writing the documentation for everything (the hardest and least interesting part for me haha) so I will have examples and screenshots soon. 

Additionally, I agree that SSDP and auto-discovery are features that are more so expected and/or required in consumer products than in the Maker and DIY community. I do think, however, that having even just one less configuration step will help remove barriers to entry for some and allow fellow hackers to focus on the more exciting parts of their project (no offence network guys, I think networking is great). 

I am enjoying this discussion very much as well. It's refreshing to find others who are passionate about building and growing a project through collaboration and communication. I have a few ESP01s lying around collecting dust, so I plan on getting ST_Anything installed on a few of them so I can be more useful here :) 

Thanks, again!
