### ISSUE TITLE
MKR1000 not responding to ST Hub

### ISSUE THREAD

**Issue by jscott304** [DanielOgorchock/ST_Anything#89]
My Hub is 192.168.1.3 and the MKR1000 is 192.168.0.9
The Arduino program is running and the log looks good 
[Enter the following three lines of data into ST App on your phone….pdf](https://github.com/DanielOgorchock/ST_Anything/files/1463535/Enter.the.following.three.lines.of.data.into.ST.App.on.your.phone.pdf)

The hub is sending packets to the arduino but not responding
![image](https://user-images.githubusercontent.com/24324316/32687425-f4635002-c678-11e7-8b9a-136456565b88.png)

![image](https://user-images.githubusercontent.com/24324316/32687431-37c4cd62-c679-11e7-8099-c4d191108f7f.png)

Thanks for your Help

**Comment by ogiewon** [comment]
Based on the data you included, it appears that the HUB might be on a different network than the MKR1000 board (192.168.1.x vs 192.168.0.x).  To know for sure, I need to know what TCP/IP Subnet Mask and Gateway you used for the MKR1000 and the HUB.

A quick test would be to use a computer that is on the same network as the hub (i.e. it would need to have an address like 192.168.1.x) to ping the MKR1000 board and see if you get any replies.  If not, then the issue lies in the TCP/IP network addressing scheme.

Also, one issue that often trips up new users is that they enter the MAC address of the Arduino incorrectly into the ST App on their phone.  Please be sure to use all UPPERCASE and remove all of the ":" delimiters.  This is not your current problem as your MKR1000 is not yet receiving the "refresh" commands at all yet from the hub.

Most home users' networks are a single LAN, with no local routing between devices.  Typical home router configuration allows for ~255 devices to be on the network.  If your router's LAN subnet mask is 255.255.255.0, then neither it or your ST Hub  will not be able to talk to your MKR1000 since it is not using a 192.168.1.x address.

**Comment by jscott304** [comment]
The hub and Arduino are on different subnets wired vs WiFi. The network settings in the hub are IP 192.168.1.3 netmask 255.255.255.0 gateway 192.168.1.1; in the Arduino they are IP 192.168.0.9 netmask 255.255.255.0 gateway 192.168.0.1. I am able to ping both the hub and Arduino from my computer when on WiFi or wired. The router has no restrictions between the networks. From the logs on the router it seems like the Arduino is not attempting to connect to the hub.


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by ogiewon** [comment]
Others have had similar issues. I recommend you try putting the hub and Arduino on the same subnet to see if that resolves the problem. If it does, you can the start troubleshooting your network and router settings to see if the is a way to resolve the problem.

**Comment by jscott304** [comment]
After rebuilding my network so wifi and wired are on the same subnet the Arduino is behaving as expected. I suspect there is an issue with either the ST Hub or ST Anything and communicating through a Router.

**Comment by ogiewon** [comment]
Glad to hear it is working.  If you ever figure out what the routing issue is, please let me know.  

ST_Anything supports quite a variety of network connected devices from various manufacturers using what I believe to be the best Arduino Libraries for Ethernet and WiFi available for each platform.  It is possible that the routing issues could lie within those libraries as well.  Personally, I have been very disappointed in the support and reliability of the WiFi 101 library and its associated WiFi chip's firmware from Atmel.  I have spent a lot of time and have added quite of recovery logic to the WiFi 101 ST_Anything specific software to try to make it run reliably.  Until Atmel updates their WiFi ship firmware, and the WiFi101 library is improved, I am weary of trusting the MKR1000 with anything that requires a lot of uptime.  I really hope YMMV for the better!  IF you start running into WiFi disconnect issues, I recommend you try the NodeMCU ESP8266 or ESP32 boards.  The ESP8266 based boards are by far the most stable and reliable WiFi connected devices I have tested.
