### ISSUE TITLE
Children not loading 

### ISSUE THREAD

**Issue by ItsDLite** [DanielOgorchock/ST_Anything#90]
I am also having an issue with Child Devices not listing under the Parent in the SmartThings webpage. I have tried the following:
Removing the Parent and all Children, rebooting the hub, removing all items from GitHub and reassigning them to my SmartThings hub. I am seeing that the refresh is causing the code in Arduino to refresh, but my individual smartThings "children" never add back into the device listing or under 'child devices"

How do I manually add a device back into a parent in the "My Devices"?

**Comment by ogiewon** [comment]
There is no manual way to create child devices. The parent must do it programmatically. 

Did you set the MAC address of the Microcontroller correctly in the Parent Device's settings in your phone app?  All uppercase and no delimiters. 

Did you set the hub's TCP/IP address correctly in the Parent?  

What does Live Logging in the ST IDE show when you hit refresh on the Parent?

**Comment by ogiewon** [comment]
Also, are the hub and microcontroller on the same subnet?

Can you ping the hub and microcontroller from a computer on the same network?

**Comment by ItsDLite** [comment]
YOU ARE A GENIUS! 
Thank you so much for the quick response. Yes, after blowing away the children and needing to rebuild the parent I made a mistake and placed delimiters in the MAC addressing on the App. Once I made your suggested change I was good to go!

**Comment by ItsDLite** [comment]
May I ask a follow up question of you please. Is there a way in the code to send notifications via SmartThings? In my code I was using a push message to tamboo, but would be nice if I could send an alert notification via SmartThings and remove Tamboo. 
Thanks so much for your help!

**Comment by vseven** [comment]
What are you trying to send an alert based on? If it's a contact sensor or something like that you can use the built-in smart home monitor function of smart things. It allows you to set up custom rules and based on those custom rules you can send alerts.

**Comment by ItsDLite** [comment]
Background: I have an Arduino Mega with Nextion touch screen wired to motion and door switches and a speaker for audio notifications. The Nextion is programmed to Arm, Disarm. I was using Tamboo to interface with the phone for arming, disarming, remote cancellation and notification of the arm going off. 

from your suggestion, I guess I would use the "button" as a flag/trigger of the arm going off or not and build a routine to send the notification?

End goal I was trying to get somewhere similar to this: (But I don't know Groovy)
I'm guessing he is using this code. 
https://www.kickstarter.com/projects/nateclark/konnected-alarm-panel-revive-your-wired-alarm-syst?ref=discovery

**Comment by ogiewon** [comment]
Yes, you can achieve exactly the same thing that Konnected offers using ST_Anything instead.  I even have sample Arduino sketches in the ST_Anything github repository that are specifically designed for Alarm Panel replacement.   

In the SmartThings architecture, you have DEVICE HANDLERS and SMARTAPPS.  Both Konnected and ST_Anything provide ready to use Device Handlers.  Everything else is native SmartThings SmartApp functionality.  The "Smart Home Monitor" can provide basic home security arming/disarming, monitoring, alarming, and notifications.

Neither solution provides a ready-built means to utilize your touchscreen, however ST_Anything does at least afford you the option to customize and add capability as you see fit. 

Neither solution (out of the box) is a standalone home security system.  Both rely on SmartThings to provide the "brains" for monitoring door, windows, and motion sensors.  If you want true local control for alarming, then you may be better off using your existing Arduino code, removing the Tamboo connections, and replacing them with one of my "SmartThings..." Arduino communications libraries (which is how ST_Anything communicates to ST as well!)  You still would not need to write any groovy code, as my Parent/Child Device Handlers will still work exactly the same.  You would just need to follow the naming convention when sending data updates to ST.

It really depends on what your requirements are.  Do you want your Arduino to replicate your old alarm panel functionality and just send updates to ST?  Or, do you want to let SmartThings handle all alarming functionality and let the Arduino just be a data bridge for sensors and sirens?

My "ST_Anything" and "SmartThings..." Arduino libraries allow you to easily build a custom solution that meets your requirements.  Use it as is with minimal programming effort, or go deep into the Arduino programming IDE to build a truly custom solution that provides the same functionality as a traditional alarm panel, with data updates to ST for easy notifications to your phone.

"Konnected" does not use the Arduino IDE, and is designed to simply bridge your sensors and siren to the SmartThings cloud.  You could customize it as it is open source, but you'll have to learn the ESP IDE if you're not familiar with it.  You would also probably need to get into the groovy code as well, if you want to support the plethora of devices already natively supported by ST_Anything.

Both solutions have Pros and Cons.  

I feel Konnected is a great "no programming required" solution which is very attractive to many users, and is being built as a for-profit business.  It also only supports the ESP8266 microcontroller, which I believe is somewhat limiting (only 6 inputs supported.)  Since Nate developed his code specifically for the ESP8266 platform, porting the code to other microcontrollers is a non-trivial exercise.    

"ST_Anything" is truly designed for for the DIY programming enthusiast/hobbyist.  You need to roll up you sleeves and get into the Arduino IDE at least a little bit (network settings, pin assignments, device declarations, etc...), but it keeps the ST Groovy Side of things trivial.  @vseven has made some significant contributions to ST_Anything over the past few months, expanding its support for more devices and we even added the ESP32 microcontroller to the mix as well.  Since I chose the Arduino IDE as my platform, it opens up the number of microcontrollers that can be supported to anything that can be programmed by the Arduino IDE, including the ESP8266, ESP32, and all of the Arduinos.

**Comment by ItsDLite** [comment]
I will try loading the ST_Anything_AlarmPanel_ESP8266WiFi Sketch and modify the code to work with the ST_Anything_Multiples_EthernetW5100 shield and see how it works with SmartThings. Thank you for all the suggestions and support! I'll keep you posted and I do prefer the DIY of ST_anything!

**Comment by ogiewon** [comment]
If you compare the two sketches, you'll see that it is probably simpler to edit the W5100 Multiples sketch to remove all of the example devices that you don't want, and then add additional contact sensors, motion detectors, etc...  

One word of caution doing this.  If you do the above, it is actually easiest to just delete the parent device in SmartThings (which also deletes all of the example child devices) and then manually create the parent again.  I say this due to some strange behavior in the ST cloud where if you manually delete a child, it seems to break all updates from the Arduino to the ST Cloud for about 24 hours (at least it did, a few months ago!)

**Comment by ItsDLite** [comment]
LOL: I've done that already actually "removing the unneeded children"  that's how I broke it round one.

**Comment by ItsDLite** [comment]
Okay, I was able to merge the ST_anything_AlarmPanel with EthernetW5100. Everything is testing out fine. I guess my next question is how to send notifications via Ardunio to a native IPhone notification and SMS via SmartThings. I tried the suggestion by vseven and built a routine for a "automatically perform "Alarm Triggered!"", "Something Turns On or Off," "SEC (alarm1), "Push Notification" & "Additionally, also send text message to:" 

The problem: The notification appears in Smartthings only and I don't get any text SMS messages.

**My goal** is once a sensor is triggered the Arduino sends an update to SEC alarm1 which SmartThings then sends out a notification over SMS and on the phones native Notification. 

---- 
My assumption in this is based on what I am reading is your code doesn't handle alarming codes, disarming codes, etc. It's limited to contact sensors being triggered for a specific time duration before triggering a relay to set off a siren/strobe.

**Comment by ogiewon** [comment]
ST_Anything does not handle any "alarming" whatsoever.  SmartThings is handling all of that.  ST_Anything is simply a bridge between the physical devices and the SmartThings platform.  SmartThings handles all of the monitoring, alarm detection, notifications, etc... ST_Anything handles communicating with the door, window, and motions sensors.  It can also activate a siren device. 

Most people just use the "Smart Home Moinitor" app natively provided by SmartThings to handle the alarming, siren activation, and notification capabilities.

**Comment by ItsDLite** [comment]
Interesting, I just set that up... never used "Smart Home Monitor" before. 

Does your Code allow Arduino to use the Armed (AWAY), Armed (HOME), Disarmed?

Meaning can I send a command via Arduino to Arm and Disarm "Smart Home Monitor" ?

**Comment by ItsDLite** [comment]
After re-reading you post it sounds like it can't sorry I didn't read that the first time

**Comment by ogiewon** [comment]
Closing for now due to lack of activity.  If you still have question, please comment here and we can re-open this issue if necessary.
